version: "3.9"

volumes:
  db:

services:
  db:
    image: postgres:14.4
    volumes:
      - 'db:/var/lib/postgresql/data'
    environment:
      - POSTGRES_PASSWORD=123456
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    depends_on:
      - db
    stdin_open: true
    tty: true
    env_file: app.env
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '10'
